let a=2;
let b=3;

console.log(a+b);
console.log(a+b);
console.log(a+b);
// Exception Handling
// try-catch block
try{
    console.log(a+c);
}
catch(err){
    console.log(err);
    
}
console.log(a+b);
console.log(a+b);
console.log(a+b);
console.log(a+b);